[package]
authors = ["Bjorn Tipling <bjorn@ambientchill.com>"]
name = "rock-paper-sissors"
version = "0.1.0"

[dependencies]
rand = "0.3.15"
term-painter = "0.2.3"

[dependencies.clap]
features = ["yaml"]
version = "~2.20.3"
