[package]
name = "rock-paper-sissors"
version = "0.1.0"
authors = ["Bjorn Tipling <bjorn@ambientchill.com>"]

[dependencies]
clap = { version = "~2.20.3", features = ["yaml"] }
term-painter = "0.2.3"
